// <auto-generated />
namespace CedroBackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TabelaPrato : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TabelaPrato));
        
        string IMigrationMetadata.Id
        {
            get { return "201803132209344_TabelaPrato"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
